# Use a base image with OpenJDK 21
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy Gradle wrapper and configuration files
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

# Download Gradle dependencies
RUN ./gradlew build -x test --parallel --continue

# Copy the rest of the application
COPY src ./src

# Build the application
RUN ./gradlew build -x test

# Expose the port the backend runs on
EXPOSE 8080

# Start the backend application
ENTRYPOINT ["java", "-jar", "build/libs/image-resizer-0.0.1-SNAPSHOT.jar"]
